version: "3.9"
services:
  db:
    container_name: lokimo_data
    image: postgis/postgis
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=LokimoTest
    volumes:
      - ./data:/var/lib/postgresql/data
      - postgre-backup:/data/data-backup

  server:
    container_name: lokimo_app
    build: .
    restart: unless-stopped
    command: sh -c "sleep 5 &&  \
      python manage.py makemigrations models && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:${API_PORT}"
    volumes:
      - ./LokimoTest:/LokimoTest
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/LokimoTest/static/
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - PG_DB=LokimoTest
      - PG_USER=admin
      - PG_MDP=admin
      - PG_HOST=db
      - PG_PORT=5432
      - ENV=DEV_DOCKER
    depends_on:
      - db

volumes:
  uwsgi_data:
  web_static:
  postgre-backup: