# Generated by Django 3.2.9 on 2022-11-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField(max_length=100)),
                ('good_id', models.TextField(max_length=100)),
                ('iris', models.TextField(max_length=100)),
                ('data', models.JSONField()),
                ('house', models.BooleanField()),
                ('buy', models.BooleanField()),
                ('last_date', models.DateField()),
                ('first_date', models.DateField()),
                ('meter_square', models.FloatField()),
                ('position', models.JSONField()),
                ('price', models.FloatField()),
                ('rooms', models.FloatField()),
                ('surface', models.FloatField()),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['ad_id'], name='models_ad_ad_id_4f1e53_idx'),
        ),
    ]
